# .streamlit/secrets.toml

[mysq2]
host = "localhost"
port = 3306
database = "pack_db"
user = "root"
password = "mahalo"
# แก้ปัญหา error NotSupportedError: Authentication plugin 'caching_sha2_password' is not supported
#auth_plugin="mysql_native_password"

[mysql]
host = "192.168.1.10"
port = 3306
database = "pack_db"
user = "root"
password = "mahalo"

[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"
